//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.261
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Bluevia.Location.Schemas {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ClientException", Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IsNullable=false)]
    public partial class ClientExceptionType {
        
        private ClientExceptionTypeExceptionCategory exceptionCategoryField;
        
        private int exceptionIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <remarks/>
        public ClientExceptionTypeExceptionCategory exceptionCategory {
            get {
                return this.exceptionCategoryField;
            }
            set {
                this.exceptionCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum ClientExceptionTypeExceptionCategory {
        
        /// <remarks/>
        SVC,
        
        /// <remarks/>
        POL,
        
        /// <remarks/>
        SEC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ServerException", Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IsNullable=false)]
    public partial class ServerExceptionType {
        
        private ServerExceptionTypeExceptionCategory exceptionCategoryField;
        
        private int exceptionIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <remarks/>
        public ServerExceptionTypeExceptionCategory exceptionCategory {
            get {
                return this.exceptionCategoryField;
            }
            set {
                this.exceptionCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum ServerExceptionTypeExceptionCategory {
        
        /// <remarks/>
        SVR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("terminalLocation", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class TerminalLocationListType {
        
        private LocationDataType[] terminalLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("terminalLocation")]
        public LocationDataType[] terminalLocation {
            get {
                return this.terminalLocationField;
            }
            set {
                this.terminalLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("terminalLocation", Namespace = "http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable = false)]
    public partial class LocationDataType {
        
        private UserIdType locatedPartyField;
        
        private RetrievalStatusType reportStatusField;
        
        private LocationInfoType currentLocationField;
        
        private ServiceErrorType errorInformationField;
        
        /// <remarks/>
        public UserIdType locatedParty {
            get {
                return this.locatedPartyField;
            }
            set {
                this.locatedPartyField = value;
            }
        }
        
        /// <remarks/>
        public RetrievalStatusType reportStatus {
            get {
                return this.reportStatusField;
            }
            set {
                this.reportStatusField = value;
            }
        }
        
        /// <remarks/>
        public LocationInfoType currentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                this.currentLocationField = value;
            }
        }
        
        /// <remarks/>
        public ServiceErrorType errorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class UserIdType {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alias", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("anyUri", typeof(string), DataType="anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("ipAddress", typeof(IpAddressType))]
        [System.Xml.Serialization.XmlElementAttribute("otherId", typeof(OtherIdType))]
        [System.Xml.Serialization.XmlElementAttribute("phoneNumber", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class IpAddressType {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ipv4", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ipv6", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        ipv4,
        
        /// <remarks/>
        ipv6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class OtherIdType {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        alias,
        
        /// <remarks/>
        anyUri,
        
        /// <remarks/>
        ipAddress,
        
        /// <remarks/>
        otherId,
        
        /// <remarks/>
        phoneNumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public enum RetrievalStatusType {
        
        /// <remarks/>
        Retrieved,
        
        /// <remarks/>
        NotRetrieved,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public partial class LocationInfoType {
        
        private CoordinatesType coordinatesField;
        
        private float altitudeField;
        
        private bool altitudeFieldSpecified;
        
        private int accuracyField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public CoordinatesType coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
        
        /// <remarks/>
        public float altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public partial class CoordinatesType {
        
        private float latitudeField;
        
        private float longitudeField;
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public partial class ServiceErrorType {
        
        private string messageIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <remarks/>
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("terminalDistance", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class TerminalDistanceType {
        
        private int distanceField;
        
        private int accuracyField;
        
        private bool accuracyFieldSpecified;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        public int distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public int accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accuracySpecified {
            get {
                return this.accuracyFieldSpecified;
            }
            set {
                this.accuracyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("geographicalNotificationSubscriptions", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class GeographicalNotificationSubscriptionsType {
        
        private SimpleReferenceType referenceField;
        
        private UserIdType requesterField;
        
        private UserIdType[] locatedPartyField;
        
        private CoordinatesType coordinatesField;
        
        private float radiusField;
        
        private float trackingAccuracyField;
        
        private EnteringLeavingCriteriaType enteringLeavingCriteriaField;
        
        private bool checkInmediateField;
        
        private TimeMetricType frequencyField;
        
        private TimeMetricType durationField;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        public SimpleReferenceType reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public UserIdType requester {
            get {
                return this.requesterField;
            }
            set {
                this.requesterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locatedParty")]
        public UserIdType[] locatedParty {
            get {
                return this.locatedPartyField;
            }
            set {
                this.locatedPartyField = value;
            }
        }
        
        /// <remarks/>
        public CoordinatesType coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
        
        /// <remarks/>
        public float radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        public float trackingAccuracy {
            get {
                return this.trackingAccuracyField;
            }
            set {
                this.trackingAccuracyField = value;
            }
        }
        
        /// <remarks/>
        public EnteringLeavingCriteriaType enteringLeavingCriteria {
            get {
                return this.enteringLeavingCriteriaField;
            }
            set {
                this.enteringLeavingCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public bool checkInmediate {
            get {
                return this.checkInmediateField;
            }
            set {
                this.checkInmediateField = value;
            }
        }
        
        /// <remarks/>
        public TimeMetricType frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        public TimeMetricType duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class SimpleReferenceType {
        
        private string endpointField;
        
        private string correlatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public enum EnteringLeavingCriteriaType {
        
        /// <remarks/>
        Entering,
        
        /// <remarks/>
        Leaving,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public partial class TimeMetricType {
        
        private TimeMetricsType metricField;
        
        private float unitsField;
        
        /// <remarks/>
        public TimeMetricsType metric {
            get {
                return this.metricField;
            }
            set {
                this.metricField = value;
            }
        }
        
        /// <remarks/>
        public float units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public enum TimeMetricsType {
        
        /// <remarks/>
        Millisecond,
        
        /// <remarks/>
        Second,
        
        /// <remarks/>
        Minute,
        
        /// <remarks/>
        Hour,
        
        /// <remarks/>
        Day,
        
        /// <remarks/>
        Week,
        
        /// <remarks/>
        Month,
        
        /// <remarks/>
        Year,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("periodicNotificationSubscriptions", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class PeriodicNotificationSubscriptionsType {
        
        private SimpleReferenceType referenceField;
        
        private UserIdType requesterField;
        
        private UserIdType[] locatedPartyField;
        
        private int requestedAccuracyField;
        
        private float radiusField;
        
        private TimeMetricType frequencyField;
        
        private TimeMetricType durationField;
        
        /// <remarks/>
        public SimpleReferenceType reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public UserIdType requester {
            get {
                return this.requesterField;
            }
            set {
                this.requesterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locatedParty")]
        public UserIdType[] locatedParty {
            get {
                return this.locatedPartyField;
            }
            set {
                this.locatedPartyField = value;
            }
        }
        
        /// <remarks/>
        public int requestedAccuracy {
            get {
                return this.requestedAccuracyField;
            }
            set {
                this.requestedAccuracyField = value;
            }
        }
        
        /// <remarks/>
        public float radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        public TimeMetricType frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        public TimeMetricType duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("distanceNotificationSubscriptions", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class DistanceNotificationSubscriptionsType {
        
        private SimpleReferenceType referenceField;
        
        private UserIdType requesterField;
        
        private UserIdType[] referenceAddressField;
        
        private UserIdType[] monitoredAddressField;
        
        private float distanceField;
        
        private float trackingAccuracyField;
        
        private DistanceCriteriaType criteriaField;
        
        private bool checkInmediateField;
        
        private TimeMetricType frequencyField;
        
        private TimeMetricType durationField;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        public SimpleReferenceType reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public UserIdType requester {
            get {
                return this.requesterField;
            }
            set {
                this.requesterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referenceAddress")]
        public UserIdType[] referenceAddress {
            get {
                return this.referenceAddressField;
            }
            set {
                this.referenceAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("monitoredAddress")]
        public UserIdType[] monitoredAddress {
            get {
                return this.monitoredAddressField;
            }
            set {
                this.monitoredAddressField = value;
            }
        }
        
        /// <remarks/>
        public float distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public float trackingAccuracy {
            get {
                return this.trackingAccuracyField;
            }
            set {
                this.trackingAccuracyField = value;
            }
        }
        
        /// <remarks/>
        public DistanceCriteriaType criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
        
        /// <remarks/>
        public bool checkInmediate {
            get {
                return this.checkInmediateField;
            }
            set {
                this.checkInmediateField = value;
            }
        }
        
        /// <remarks/>
        public TimeMetricType frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        public TimeMetricType duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public enum DistanceCriteriaType {
        
        /// <remarks/>
        AllWithinDistance,
        
        /// <remarks/>
        AnyWithinDistance,
        
        /// <remarks/>
        AllBeyondDistance,
        
        /// <remarks/>
        AnyBeyondDistance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("locationNotification", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class LocationNotificationType {
        
        private SimpleReferenceType referenceField;
        
        private LocationDataType[] dataField;
        
        private EnteringLeavingCriteriaType enteringLeavingCriteriaField;
        
        private bool enteringLeavingCriteriaFieldSpecified;
        
        private DistanceCriteriaType distanceCriteriaField;
        
        private bool distanceCriteriaFieldSpecified;
        
        private bool isFinalNotificationField;
        
        private bool isFinalNotificationFieldSpecified;
        
        /// <remarks/>
        public SimpleReferenceType reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public LocationDataType[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public EnteringLeavingCriteriaType enteringLeavingCriteria {
            get {
                return this.enteringLeavingCriteriaField;
            }
            set {
                this.enteringLeavingCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enteringLeavingCriteriaSpecified {
            get {
                return this.enteringLeavingCriteriaFieldSpecified;
            }
            set {
                this.enteringLeavingCriteriaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DistanceCriteriaType distanceCriteria {
            get {
                return this.distanceCriteriaField;
            }
            set {
                this.distanceCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distanceCriteriaSpecified {
            get {
                return this.distanceCriteriaFieldSpecified;
            }
            set {
                this.distanceCriteriaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isFinalNotification {
            get {
                return this.isFinalNotificationField;
            }
            set {
                this.isFinalNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFinalNotificationSpecified {
            get {
                return this.isFinalNotificationFieldSpecified;
            }
            set {
                this.isFinalNotificationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("subscriptionCancellationNotification", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class SubscriptionCancellationNotificationType {
        
        private UserIdType addressField;
        
        private SimpleReferenceType referenceField;
        
        private ServiceErrorType reasonField;
        
        /// <remarks/>
        public UserIdType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public SimpleReferenceType reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public ServiceErrorType reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("terminalAddress", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class TerminalAddressListType {
        
        private AddressDataType[] terminalAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("terminalAddress")]
        public AddressDataType[] terminalAddress {
            get {
                return this.terminalAddressField;
            }
            set {
                this.terminalAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    public partial class AddressDataType {
        
        private UserIdType terminalNumberField;
        
        private AddressType currentAddressField;
        
        /// <remarks/>
        public UserIdType terminalNumber {
            get {
                return this.terminalNumberField;
            }
            set {
                this.terminalNumberField = value;
            }
        }
        
        /// <remarks/>
        public AddressType currentAddress {
            get {
                return this.currentAddressField;
            }
            set {
                this.currentAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class AddressType {
        
        private string streetField;
        
        private uint streetNumberField;
        
        private bool streetNumberFieldSpecified;
        
        private string localityField;
        
        private string regionField;
        
        private uint postalCodeField;
        
        private bool postalCodeFieldSpecified;
        
        private string countryField;
        
        private string extField;
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public uint streetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool streetNumberSpecified {
            get {
                return this.streetNumberFieldSpecified;
            }
            set {
                this.streetNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public uint postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postalCodeSpecified {
            get {
                return this.postalCodeFieldSpecified;
            }
            set {
                this.postalCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string ext {
            get {
                return this.extField;
            }
            set {
                this.extField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("terminalDistanceFromAddress", Namespace="http://www.telefonica.com/schemas/UNICA/REST/location/v1/", IsNullable=false)]
    public partial class TerminalDistanceFromAddressType {
        
        private int distanceField;
        
        /// <remarks/>
        public int distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
    }
}
