//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Bluevia.Payment.Schemas {
    using System.Xml.Serialization;
    
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MethodCallType", Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    [System.Xml.Serialization.XmlRootAttribute("methodCall", Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1", IsNullable=false)]
    public partial class MethodCallType1 : MethodCallType {
        
        private MethodType methodField;
        
        private MethodCallTypeParams paramsField;
        
        
        public MethodType method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        
        public MethodCallTypeParams @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public enum MethodType {
        
        
        PAYMENT,
        
        
        CANCEL_AUTHORIZATION,
        
        
        REFUND,
        
        
        GET_PAYMENT_STATUS,
        
        
        NOTIFY_PAYMENT_FINAL_STATUS,
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class MethodCallTypeParams {
        
        private object itemField;
        
        
        [System.Xml.Serialization.XmlElementAttribute("getPaymentStatusParams", typeof(GetPaymentStatusParamsType))]
        [System.Xml.Serialization.XmlElementAttribute("notifyPaymentFinalStatusParams", typeof(NotifyPaymentFinalStatusParamsType))]
        [System.Xml.Serialization.XmlElementAttribute("paymentParams", typeof(PaymentParamsType))]
        [System.Xml.Serialization.XmlElementAttribute("refundParams", typeof(RefundParamsType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class GetPaymentStatusParamsType {
        
        private string transactionIdField;
        
        
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class GetPaymentStatusResultType {
        
        private string transactionStatusField;
        
        private string transactionStatusDescriptionField;
        
        private System.Xml.XmlElement[] anyField;
        
        
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        
        public string transactionStatusDescription {
            get {
                return this.transactionStatusDescriptionField;
            }
            set {
                this.transactionStatusDescriptionField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class PaymentResultType {
        
        private string transactionIdField;
        
        private string transactionStatusField;
        
        private string transactionStatusDescriptionField;
        
        private System.Xml.XmlElement[] anyField;
        
        
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        
        public string transactionStatusDescription {
            get {
                return this.transactionStatusDescriptionField;
            }
            set {
                this.transactionStatusDescriptionField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/definition/v1")]
    public partial class ErrorType {
        
        private string codeField;
        
        private string messageField;
        
        private string[] dataField;
        
        
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public string[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MethodResponseType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/definition/v1")]
    public partial class MethodResponseType {
        
        private string idField;
        
        private string versionField;
        
        private ErrorType errorField;
        
        
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        
        public ErrorType error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class NotifyPaymentFinalStatusParamsType {
        
        private string transactionIdField;
        
        private string transactionStatusField;
        
        private string transactionStatusDescriptionField;
        
        private System.Xml.XmlElement[] anyField;
        
        
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        
        public string transactionStatusDescription {
            get {
                return this.transactionStatusDescriptionField;
            }
            set {
                this.transactionStatusDescriptionField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class RefundParamsType {
        
        private UserIdType endUserIdentifierField;
        
        private string transactionIdField;
        
        private string reasonField;
        
        
        public UserIdType endUserIdentifier {
            get {
                return this.endUserIdentifierField;
            }
            set {
                this.endUserIdentifierField = value;
            }
        }
        
        
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/common/v1")]
    public partial class UserIdType {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        
        [System.Xml.Serialization.XmlElementAttribute("alias", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("anyUri", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ipAddress", typeof(IpAddressType))]
        [System.Xml.Serialization.XmlElementAttribute("otherId", typeof(OtherIdType))]
        [System.Xml.Serialization.XmlElementAttribute("phoneNumber", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/common/v1")]
    public partial class IpAddressType {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        
        [System.Xml.Serialization.XmlElementAttribute("ipv4", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ipv6", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/common/v1", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        
        ipv4,
        
        
        ipv6,
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/common/v1")]
    public partial class OtherIdType {
        
        private string typeField;
        
        private string valueField;
        
        
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/common/v1", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        
        alias,
        
        
        anyUri,
        
        
        ipAddress,
        
        
        otherId,
        
        
        phoneNumber,
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/common/v1")]
    public partial class SimpleReferenceType {
        
        private string endpointField;
        
        private string correlatorField;
        
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class PaymentInfoType {
        
        private UserIdType endUserIdentifierField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private decimal taxesField;
        
        private bool taxesFieldSpecified;
        
        private string codeField;
        
        private string referencecodeField;
        
        private string descriptionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        
        public UserIdType endUserIdentifier {
            get {
                return this.endUserIdentifierField;
            }
            set {
                this.endUserIdentifierField = value;
            }
        }
        
        
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        
        public decimal taxes {
            get {
                return this.taxesField;
            }
            set {
                this.taxesField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxesSpecified {
            get {
                return this.taxesFieldSpecified;
            }
            set {
                this.taxesFieldSpecified = value;
            }
        }
        
        
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        
        public string referencecode {
            get {
                return this.referencecodeField;
            }
            set {
                this.referencecodeField = value;
            }
        }
        
        
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class PaymentParamsType {
        
        private System.DateTime timestampField;
        
        private PaymentInfoType paymentInfoField;
        
        private SimpleReferenceType receiptRequestField;
        
        
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        
        public PaymentInfoType paymentInfo {
            get {
                return this.paymentInfoField;
            }
            set {
                this.paymentInfoField = value;
            }
        }
        
        
        public SimpleReferenceType receiptRequest {
            get {
                return this.receiptRequestField;
            }
            set {
                this.receiptRequestField = value;
            }
        }
    }
    
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MethodCallType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/RPC/definition/v1")]
    public partial class MethodCallType {
        
        private string idField;
        
        private string versionField;
        
        
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MethodResponseType", Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    [System.Xml.Serialization.XmlRootAttribute("methodResponse", Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1", IsNullable=false)]
    public partial class MethodResponseType1 : MethodResponseType {
        
        private MethodResponseTypeResult resultField;
        
        
        public MethodResponseTypeResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/RPC/payment/v1")]
    public partial class MethodResponseTypeResult {
        
        private object itemField;
        
        
        [System.Xml.Serialization.XmlElementAttribute("getPaymentStatusResult", typeof(GetPaymentStatusResultType))]
        [System.Xml.Serialization.XmlElementAttribute("paymentResult", typeof(PaymentResultType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
