//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluevia.Resources {
    using System;
    
    
    /// <summary>
    ///   Resource class with fixed type establishment, to look for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bluevia.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It has to be at least one adrequest.
        /// </summary>
        internal static string AtLeastOneAdRequest {
            get {
                return ResourceManager.GetString("AtLeastOneAdRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Http Response ({0}).
        /// </summary>
        internal static string InvalidHttpResponse {
            get {
                return ResourceManager.GetString("InvalidHttpResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At least 2 UserInfoSearchCategories should be specified.
        /// </summary>
        internal static string InvalidNumberOfUserInfoSearchCategories {
            get {
                return ResourceManager.GetString("InvalidNumberOfUserInfoSearchCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Parse of Remote Exception.
        /// </summary>
        internal static string InvalidParseRemoteException {
            get {
                return ResourceManager.GetString("InvalidParseRemoteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It has to be one and only one adrequest.
        /// </summary>
        internal static string OnlyOneAdRequest {
            get {
                return ResourceManager.GetString("OnlyOneAdRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It can&apos;t be returned more than one ad.
        /// </summary>
        internal static string OnlyOneMaxAds {
            get {
                return ResourceManager.GetString("OnlyOneMaxAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown Error - see attached inner exception.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
