// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Bluevia.MMS.Schemas {
    using System.Xml.Serialization;
    using System.Collections.Generic;
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ClientException", Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IsNullable=false)]
    public partial class ClientExceptionType {
        
        private ClientExceptionTypeExceptionCategory exceptionCategoryField;
        
        private int exceptionIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <comentarios/>
        public ClientExceptionTypeExceptionCategory exceptionCategory {
            get {
                return this.exceptionCategoryField;
            }
            set {
                this.exceptionCategoryField = value;
            }
        }
        
        /// <comentarios/>
        public int exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <comentarios/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum ClientExceptionTypeExceptionCategory {
        
        /// <comentarios/>
        SVC,
        
        /// <comentarios/>
        POL,
        
        /// <comentarios/>
        SEC,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ServerException", Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IsNullable=false)]
    public partial class ServerExceptionType {
        
        private ServerExceptionTypeExceptionCategory exceptionCategoryField;
        
        private int exceptionIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <comentarios/>
        public ServerExceptionTypeExceptionCategory exceptionCategory {
            get {
                return this.exceptionCategoryField;
            }
            set {
                this.exceptionCategoryField = value;
            }
        }
        
        /// <comentarios/>
        public int exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <comentarios/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum ServerExceptionTypeExceptionCategory {
        
        /// <comentarios/>
        SVR,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("message", Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", IsNullable=false)]
    public partial class MessageType {
        
        private UserIdType[] addressField;
        
        private SimpleReferenceType receiptRequestField;
        
        private string senderNameField;
        
        private UserIdType originAddressField;
        
        private string subjectField;
        
        private string priorityField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public UserIdType[] address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <comentarios/>
        public SimpleReferenceType receiptRequest {
            get {
                return this.receiptRequestField;
            }
            set {
                this.receiptRequestField = value;
            }
        }
        
        /// <comentarios/>
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
            }
        }
        
        /// <comentarios/>
        public UserIdType originAddress {
            get {
                return this.originAddressField;
            }
            set {
                this.originAddressField = value;
            }
        }
        
        /// <comentarios/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <comentarios/>
        public string priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class UserIdType {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("alias", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("anyUri", typeof(string), DataType="anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("ipAddress", typeof(IpAddressType))]
        [System.Xml.Serialization.XmlElementAttribute("otherId", typeof(OtherIdType))]
        [System.Xml.Serialization.XmlElementAttribute("phoneNumber", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class IpAddressType {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ipv4", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ipv6", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <comentarios/>
        ipv4,
        
        /// <comentarios/>
        ipv6,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class OtherIdType {
        
        private string typeField;
        
        private string valueField;
        
        /// <comentarios/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <comentarios/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <comentarios/>
        alias,
        
        /// <comentarios/>
        anyUri,
        
        /// <comentarios/>
        ipAddress,
        
        /// <comentarios/>
        otherId,
        
        /// <comentarios/>
        phoneNumber,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class SimpleReferenceType {
        
        private string endpointField;
        
        private string correlatorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <comentarios/>
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("messageDeliveryStatus", Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", IsNullable=false)]
    public partial class MessageDeliveryStatusType {
        
        private DeliveryInformationType[] messageDeliveryStatusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("messageDeliveryStatus")]
        public DeliveryInformationType[] messageDeliveryStatus {
            get {
                return this.messageDeliveryStatusField;
            }
            set {
                this.messageDeliveryStatusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    public partial class DeliveryInformationType {
        
        private UserIdType addressField;
        
        private string deliveryStatusField;
        
        private string descriptionField;
        
        /// <comentarios/>
        public UserIdType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <comentarios/>
        public string deliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
            }
        }
        
        /// <comentarios/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("receivedMessages", Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", IsNullable=false)]
    public partial class ReceivedMessagesType {
        
        private MessageReferenceType[] receivedMessagesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("receivedMessages")]
        public MessageReferenceType[] receivedMessages {
            get {
                return this.receivedMessagesField;
            }
            set {
                this.receivedMessagesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    public partial class MessageReferenceType {
        
        private string messageIdentifierField;
        
        private UserIdType destinationAddressField;
        
        private UserIdType originAddressField;
        
        private string subjectField;
        
        private string priorityField;
        
        private string messageField;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        private MessageURIType[] attachmentURLField;
        
        /// <comentarios/>
        public string messageIdentifier {
            get {
                return this.messageIdentifierField;
            }
            set {
                this.messageIdentifierField = value;
            }
        }
        
        /// <comentarios/>
        public UserIdType destinationAddress {
            get {
                return this.destinationAddressField;
            }
            set {
                this.destinationAddressField = value;
            }
        }
        
        /// <comentarios/>
        public UserIdType originAddress {
            get {
                return this.originAddressField;
            }
            set {
                this.originAddressField = value;
            }
        }
        
        /// <comentarios/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <comentarios/>
        public string priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <comentarios/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("attachmentURL")]
        public MessageURIType[] attachmentURL {
            get {
                return this.attachmentURLField;
            }
            set {
                this.attachmentURLField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    public partial class MessageURIType {
        
        private string hrefField;
        
        private string contentTypeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <comentarios/>
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("deliveryStatusUpdate", Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", IsNullable=false)]
    public partial class DeliveryStatusUpdateType {
        
        private string correlatorField;
        
        private DeliveryInformationType deliveryStatusField;
        
        /// <comentarios/>
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
        
        /// <comentarios/>
        public DeliveryInformationType deliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("deliveryReceiptNotification", Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", IsNullable=false)]
    public partial class DeliveryReceiptNotificationType {
        
        private SimpleReferenceType referenceField;
        
        private UserIdType[] originAddressField;
        
        private string filterCriteriaField;
        
        /// <comentarios/>
        public SimpleReferenceType reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("originAddress")]
        public UserIdType[] originAddress {
            get {
                return this.originAddressField;
            }
            set {
                this.originAddressField = value;
            }
        }
        
        /// <comentarios/>
        public string filterCriteria {
            get {
                return this.filterCriteriaField;
            }
            set {
                this.filterCriteriaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("receivedMessageAsync", Namespace="http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", IsNullable=false)]
    public partial class ReceivedMessageAsyncType {
        
        private string correlatorField;
        
        private MessageReferenceType messageField;
        
        /// <comentarios/>
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
        
        /// <comentarios/>
        public MessageReferenceType message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("messageNotification", Namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", IsNullable = false)]
    public partial class MessageNotificationType
    {

        private SimpleReferenceType referenceField;

        private UserIdType[] destinationAddressField;

        private string criteriaField;

        private bool useAttachmentURLsField;

        private bool useAttachmentURLsFieldSpecified;

        /// <comentarios/>
        public SimpleReferenceType reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("destinationAddress")]
        public UserIdType[] destinationAddress
        {
            get
            {
                return this.destinationAddressField;
            }
            set
            {
                this.destinationAddressField = value;
            }
        }

        /// <comentarios/>
        public string criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }

        /// <comentarios/>
        public bool useAttachmentURLs
        {
            get
            {
                return this.useAttachmentURLsField;
            }
            set
            {
                this.useAttachmentURLsField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useAttachmentURLsSpecified
        {
            get
            {
                return this.useAttachmentURLsFieldSpecified;
            }
            set
            {
                this.useAttachmentURLsFieldSpecified = value;
            }
        }
    }
}

