//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Bluevia.Directory.Schemas {
    using System.Xml.Serialization;
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ClientException", Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IsNullable=false)]
    public partial class ClientExceptionType {
        
        private ClientExceptionTypeExceptionCategory exceptionCategoryField;
        
        private int exceptionIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <comentarios/>
        public ClientExceptionTypeExceptionCategory exceptionCategory {
            get {
                return this.exceptionCategoryField;
            }
            set {
                this.exceptionCategoryField = value;
            }
        }
        
        /// <comentarios/>
        public int exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <comentarios/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum ClientExceptionTypeExceptionCategory {
        
        /// <comentarios/>
        SVC,
        
        /// <comentarios/>
        POL,
        
        /// <comentarios/>
        SEC,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    [System.Xml.Serialization.XmlRootAttribute("ServerException", Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IsNullable=false)]
    public partial class ServerExceptionType {
        
        private ServerExceptionTypeExceptionCategory exceptionCategoryField;
        
        private int exceptionIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <comentarios/>
        public ServerExceptionTypeExceptionCategory exceptionCategory {
            get {
                return this.exceptionCategoryField;
            }
            set {
                this.exceptionCategoryField = value;
            }
        }
        
        /// <comentarios/>
        public int exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <comentarios/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum ServerExceptionTypeExceptionCategory {
        
        /// <comentarios/>
        SVR,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("userInfo", Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", IsNullable=false)]
    public partial class UserInfoType {
        
        private UserIdentitiesType userIdentitiesField;
        
        private UserPersonalInfoType userPersonalInfoField;
        
        private UserProfileType userProfileField;
        
        private UserAccessInfoType userAccessInfoField;
        
        private UserTerminalInfoType userTerminalInfoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserIdentitiesType userIdentities {
            get {
                return this.userIdentitiesField;
            }
            set {
                this.userIdentitiesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserPersonalInfoType userPersonalInfo {
            get {
                return this.userPersonalInfoField;
            }
            set {
                this.userPersonalInfoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserProfileType userProfile {
            get {
                return this.userProfileField;
            }
            set {
                this.userProfileField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserAccessInfoType userAccessInfo {
            get {
                return this.userAccessInfoField;
            }
            set {
                this.userAccessInfoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserTerminalInfoType userTerminalInfo {
            get {
                return this.userTerminalInfoField;
            }
            set {
                this.userTerminalInfoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("userIdentities", Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", IsNullable=false)]
    public partial class UserIdentitiesType {
        
        private string phoneNumberField;
        
        private string telUriField;
        
        private string sipUriField;
        
        private string emailField;
        
        private IpAddressType ipAddressField;
        
        private string aliasField;
        
        private OtherIdType otherIdField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telUri {
            get {
                return this.telUriField;
            }
            set {
                this.telUriField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sipUri {
            get {
                return this.sipUriField;
            }
            set {
                this.sipUriField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IpAddressType ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OtherIdType otherId {
            get {
                return this.otherIdField;
            }
            set {
                this.otherIdField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class IpAddressType {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ipv4", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ipv6", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <comentarios/>
        ipv4,
        
        /// <comentarios/>
        ipv6,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class OtherIdType {
        
        private string typeField;
        
        private string valueField;
        
        /// <comentarios/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <comentarios/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("userPersonalInfo", Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", IsNullable=false)]
    public partial class UserPersonalInfoType {
        
        private string displayNameField;
        
        private NameType nameField;
        
        private string namePrefixField;
        
        private string nameSufixField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private System.Nullable<GenderType> genderField;
        
        private bool genderFieldSpecified;
        
        private AddressType addressField;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        private bool lastUpdatedFieldSpecified;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NameType name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string namePrefix {
            get {
                return this.namePrefixField;
            }
            set {
                this.namePrefixField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nameSufix {
            get {
                return this.nameSufixField;
            }
            set {
                this.nameSufixField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<GenderType> gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AddressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdatedSpecified {
            get {
                return this.lastUpdatedFieldSpecified;
            }
            set {
                this.lastUpdatedFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public ExtensionType extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    public partial class NameType {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        /// <comentarios/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <comentarios/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <comentarios/>
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum GenderType {
        
        /// <comentarios/>
        male,
        
        /// <comentarios/>
        female,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class AddressType {
        
        private string streetField;
        
        private uint streetNumberField;
        
        private bool streetNumberFieldSpecified;
        
        private string localityField;
        
        private string regionField;
        
        private uint postalCodeField;
        
        private bool postalCodeFieldSpecified;
        
        private string countryField;
        
        private string extField;
        
        /// <comentarios/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <comentarios/>
        public uint streetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool streetNumberSpecified {
            get {
                return this.streetNumberFieldSpecified;
            }
            set {
                this.streetNumberFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <comentarios/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <comentarios/>
        public uint postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postalCodeSpecified {
            get {
                return this.postalCodeFieldSpecified;
            }
            set {
                this.postalCodeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <comentarios/>
        public string ext {
            get {
                return this.extField;
            }
            set {
                this.extField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public partial class ExtensionType {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("userProfile", Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", IsNullable=false)]
    public partial class UserProfileType {
        
        private string userTypeField;
        
        private string imsiField;
        
        private string icbField;
        
        private string ocbField;
        
        private string languageField;
        
        private string simTypeField;
        
        private string parentalControlField;
        
        private System.Nullable<FlagType> creditControlField;
        
        private bool creditControlFieldSpecified;
        
        private string diversionMsisdnField;
        
        private string enterpriseNameField;
        
        private System.Nullable<FlagType> roamingField;
        
        private bool roamingFieldSpecified;
        
        private string operatorIdField;
        
        private System.Nullable<MmsStatusType> mmsStatusField;
        
        private bool mmsStatusFieldSpecified;
        
        private string segmentField;
        
        private string subsegmentField;
        
        private SubscribedServiceType[] subscribedServiceField;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        private bool lastUpdatedFieldSpecified;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string iccField;
        
        private string restMensField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string icb {
            get {
                return this.icbField;
            }
            set {
                this.icbField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ocb {
            get {
                return this.ocbField;
            }
            set {
                this.ocbField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string simType {
            get {
                return this.simTypeField;
            }
            set {
                this.simTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parentalControl {
            get {
                return this.parentalControlField;
            }
            set {
                this.parentalControlField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> creditControl {
            get {
                return this.creditControlField;
            }
            set {
                this.creditControlField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditControlSpecified {
            get {
                return this.creditControlFieldSpecified;
            }
            set {
                this.creditControlFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string diversionMsisdn {
            get {
                return this.diversionMsisdnField;
            }
            set {
                this.diversionMsisdnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string enterpriseName {
            get {
                return this.enterpriseNameField;
            }
            set {
                this.enterpriseNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> roaming {
            get {
                return this.roamingField;
            }
            set {
                this.roamingField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool roamingSpecified {
            get {
                return this.roamingFieldSpecified;
            }
            set {
                this.roamingFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<MmsStatusType> mmsStatus {
            get {
                return this.mmsStatusField;
            }
            set {
                this.mmsStatusField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mmsStatusSpecified {
            get {
                return this.mmsStatusFieldSpecified;
            }
            set {
                this.mmsStatusFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string segment {
            get {
                return this.segmentField;
            }
            set {
                this.segmentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subsegment {
            get {
                return this.subsegmentField;
            }
            set {
                this.subsegmentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("subscribedService", IsNullable=true)]
        public SubscribedServiceType[] subscribedService {
            get {
                return this.subscribedServiceField;
            }
            set {
                this.subscribedServiceField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdatedSpecified {
            get {
                return this.lastUpdatedFieldSpecified;
            }
            set {
                this.lastUpdatedFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public ExtensionType extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string icc {
            get {
                return this.iccField;
            }
            set {
                this.iccField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string restMens {
            get {
                return this.restMensField;
            }
            set {
                this.restMensField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/common/v1")]
    public enum FlagType {
        
        /// <comentarios/>
        yes,
        
        /// <comentarios/>
        no,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    public enum MmsStatusType {
        
        /// <comentarios/>
        activated,
        
        /// <comentarios/>
        deactivated,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    public partial class SubscribedServiceType {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("userAccessInfo", Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", IsNullable=false)]
    public partial class UserAccessInfoType {
        
        private System.Nullable<FlagType> connectedField;
        
        private bool connectedFieldSpecified;
        
        private IpAddressType ipAddressField;
        
        private string accessTypeField;
        
        private System.Nullable<uint> connectionTimeField;
        
        private bool connectionTimeFieldSpecified;
        
        private string apnField;
        
        private System.Nullable<FlagType> roamingField;
        
        private bool roamingFieldSpecified;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> connected {
            get {
                return this.connectedField;
            }
            set {
                this.connectedField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool connectedSpecified {
            get {
                return this.connectedFieldSpecified;
            }
            set {
                this.connectedFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IpAddressType ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accessType {
            get {
                return this.accessTypeField;
            }
            set {
                this.accessTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<uint> connectionTime {
            get {
                return this.connectionTimeField;
            }
            set {
                this.connectionTimeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool connectionTimeSpecified {
            get {
                return this.connectionTimeFieldSpecified;
            }
            set {
                this.connectionTimeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apn {
            get {
                return this.apnField;
            }
            set {
                this.apnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> roaming {
            get {
                return this.roamingField;
            }
            set {
                this.roamingField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool roamingSpecified {
            get {
                return this.roamingFieldSpecified;
            }
            set {
                this.roamingFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public ExtensionType extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("userTerminalInfo", Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", IsNullable=false)]
    public partial class UserTerminalInfoType {
        
        private string brandField;
        
        private string modelField;
        
        private string versionField;
        
        private string screenResolutionField;
        
        private string imeiField;
        
        private System.Nullable<FlagType> mmsField;
        
        private bool mmsFieldSpecified;
        
        private System.Nullable<FlagType> emsField;
        
        private bool emsFieldSpecified;
        
        private System.Nullable<FlagType> smartMessagingField;
        
        private bool smartMessagingFieldSpecified;
        
        private System.Nullable<FlagType> wapField;
        
        private bool wapFieldSpecified;
        
        private string ussdPhaseField;
        
        private System.Nullable<FlagType> syncMlField;
        
        private bool syncMlFieldSpecified;
        
        private string syncMlVersionField;
        
        private string emsMaxNumberField;
        
        private System.Nullable<FlagType> emailField;
        
        private bool emailFieldSpecified;
        
        private System.Nullable<FlagType> emnField;
        
        private bool emnFieldSpecified;
        
        private System.Nullable<FlagType> adc_OTAField;
        
        private bool adc_OTAFieldSpecified;
        
        private System.Nullable<StatusType> statusField;
        
        private bool statusFieldSpecified;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        private bool lastUpdatedFieldSpecified;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Nullable<FlagType> wapPushField;
        
        private bool wapPushFieldSpecified;
        
        private System.Nullable<FlagType> mmsVideoField;
        
        private bool mmsVideoFieldSpecified;
        
        private System.Nullable<FlagType> videoStreamingField;
        
        private bool videoStreamingFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string screenResolution {
            get {
                return this.screenResolutionField;
            }
            set {
                this.screenResolutionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imei {
            get {
                return this.imeiField;
            }
            set {
                this.imeiField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> mms {
            get {
                return this.mmsField;
            }
            set {
                this.mmsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mmsSpecified {
            get {
                return this.mmsFieldSpecified;
            }
            set {
                this.mmsFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> ems {
            get {
                return this.emsField;
            }
            set {
                this.emsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emsSpecified {
            get {
                return this.emsFieldSpecified;
            }
            set {
                this.emsFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> smartMessaging {
            get {
                return this.smartMessagingField;
            }
            set {
                this.smartMessagingField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smartMessagingSpecified {
            get {
                return this.smartMessagingFieldSpecified;
            }
            set {
                this.smartMessagingFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> wap {
            get {
                return this.wapField;
            }
            set {
                this.wapField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wapSpecified {
            get {
                return this.wapFieldSpecified;
            }
            set {
                this.wapFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ussdPhase {
            get {
                return this.ussdPhaseField;
            }
            set {
                this.ussdPhaseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> syncMl {
            get {
                return this.syncMlField;
            }
            set {
                this.syncMlField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool syncMlSpecified {
            get {
                return this.syncMlFieldSpecified;
            }
            set {
                this.syncMlFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syncMlVersion {
            get {
                return this.syncMlVersionField;
            }
            set {
                this.syncMlVersionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emsMaxNumber {
            get {
                return this.emsMaxNumberField;
            }
            set {
                this.emsMaxNumberField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emailSpecified {
            get {
                return this.emailFieldSpecified;
            }
            set {
                this.emailFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> emn {
            get {
                return this.emnField;
            }
            set {
                this.emnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emnSpecified {
            get {
                return this.emnFieldSpecified;
            }
            set {
                this.emnFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> adc_OTA {
            get {
                return this.adc_OTAField;
            }
            set {
                this.adc_OTAField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adc_OTASpecified {
            get {
                return this.adc_OTAFieldSpecified;
            }
            set {
                this.adc_OTAFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<StatusType> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdatedSpecified {
            get {
                return this.lastUpdatedFieldSpecified;
            }
            set {
                this.lastUpdatedFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public ExtensionType extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> wapPush {
            get {
                return this.wapPushField;
            }
            set {
                this.wapPushField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wapPushSpecified {
            get {
                return this.wapPushFieldSpecified;
            }
            set {
                this.wapPushFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> mmsVideo {
            get {
                return this.mmsVideoField;
            }
            set {
                this.mmsVideoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mmsVideoSpecified {
            get {
                return this.mmsVideoFieldSpecified;
            }
            set {
                this.mmsVideoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<FlagType> videoStreaming {
            get {
                return this.videoStreamingField;
            }
            set {
                this.videoStreamingField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool videoStreamingSpecified {
            get {
                return this.videoStreamingFieldSpecified;
            }
            set {
                this.videoStreamingFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.telefonica.com/schemas/UNICA/REST/directory/v1/")]
    public enum StatusType {
        
        /// <comentarios/>
        approved,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("not approved")]
        notapproved,
    }
}
